pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'The webhook is working!!!..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}