pipeline {
    agent { 
        label 'slave-node' 
    }
    stages {
        stage('Build') {
            steps {
                echo 'Hello my name is eeun..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
